language: ruby
rvm:
  - '2.6.6'
env:
  - DB=postgresql
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - cd ruby && gem install bundler
