language: ruby
rvm:
  - '2.1.2'
env:
  - DB=postgresql
services:
  - redis-server
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
