default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: BookLibrary_development

test:
  <<: *default
  database: BookLibrary_test

production:
  <<: *default
  database: BookLibrary_production
  username: BookLibrary
  password: <%= ENV['BOOKLIBRARY_DATABASE_PASSWORD'] %>
