name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: BookLibrary
          POSTGRES_PASSWORD: ${{ secrets.BOOKLIBRARY_DATABASE_PASSWORD }}
          POSTGRES_DB: BookLibrary_test
        ports:
        - 5432/tcp
        # Needed because the Postgres container does not provide a healthcheck.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: 'Install gems.'
      run: bundle install --jobs 4 --retry 3
    - name: 'Setup database for tests.'
      env:
        PGHOST: localhost
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        PGUSER: BookLibrary
        PGPASSWORD: ${{ secrets.BOOKLIBRARY_DATABASE_PASSWORD }}
        RAILS_ENV: test
      run: bundle exec rake db:setup
    - name: 'Run tests.'
      env:
        PGHOST: localhost
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        PGUSER: BookLibrary
        PGPASSWORD: ${{ secrets.BOOKLIBRARY_DATABASE_PASSWORD }}
        RAILS_ENV: test
      run: bundle exec rspec
